POLICIES_MASTER = {
    "POL-CANCEL-01": {
        "code": "POL-CANCEL-01",
        "category": "cancellation",
        "title": "Cancellation Rebooking & Full Refund",
        "citation": "Service Rules § 3: Cancellation Rebooking Rule",
        "rule_text": "If a flight is cancelled by the airline, the customer is entitled to a free rebooking on the next available flight within 24 hours, or a full refund, customer's choice.",
        "allowed_options": ["free_rebooking_24h", "full_refund"],
        "rebooking_window_hours": 24,
    },
    "POL-DELAY-01": {
        "code": "POL-DELAY-01",
        "category": "delay",
        "title": "Delay Compensation: Under 3 Hours",
        "citation": "Service Rules § 3: Delay Compensation Rule",
        "rule_text": "Delay under 3 hours: ₹500 meal voucher.",
        "min_delay_hours": 0.0,
        "max_delay_hours": 3.0,
        "benefits": ["₹500 meal voucher"],
    },
    "POL-DELAY-02": {
        "code": "POL-DELAY-02",
        "category": "delay",
        "title": "Delay Compensation: More Than 3 Hours",
        "citation": "Service Rules § 3: Delay Compensation Rule",
        "rule_text": "Delay more than 3 hours: meal voucher + lounge access.",
        "min_delay_hours": 3.0,
        "max_delay_hours": 5.0,
        "benefits": ["meal voucher", "lounge access"],
    },
    "POL-DELAY-03": {
        "code": "POL-DELAY-03",
        "category": "delay",
        "title": "Delay Compensation: More Than 5 Hours",
        "citation": "Service Rules § 3: Delay Compensation Rule",
        "rule_text": "Delay more than 5 hours: meal voucher + hotel accommodation, covering only the delayed hours (not a full night's stay).",
        "min_delay_hours": 5.0,
        "benefits": ["meal voucher", "lounge access", "hotel accommodation (delayed hours only)"],
        "hotel_scope": "delayed_hours_only",
    },
    "POL-REFUND-01": {
        "code": "POL-REFUND-01",
        "category": "refund",
        "title": "Refund Processing Timeline & Payment Method",
        "citation": "Service Rules § 3: Refund Processing Rule",
        "rule_text": "Refunds for airline-caused cancellations are processed in full within 7 business days. Refunds are issued to the original payment method only.",
        "processing_days": 7,
        "payment_method": "original_payment_method_only",
    },
    "POL-FARE-01": {
        "code": "POL-FARE-01",
        "category": "fare",
        "title": "Fare Difference & Waiver Threshold",
        "citation": "Service Rules § 3: Fare Difference Rule",
        "rule_text": "If a customer voluntarily chooses to rebook on a higher-fare flight (not airline-caused), they must pay the fare difference. Agents cannot waive fare differences above ₹1,500 without supervisor approval.",
        "max_agent_waiver": 1500,
    },
    "POL-LOYALTY-01": {
        "code": "POL-LOYALTY-01",
        "category": "loyalty",
        "title": "Loyalty Tier Benefits & Restrictions",
        "citation": "Service Rules § 3: Loyalty Tier Rule",
        "rule_text": "Gold and Platinum tier customers get priority rebooking (first access to next-available seats) but no additional compensation beyond the standard policy.",
        "priority_tiers": ["Gold", "Platinum"],
        "extra_compensation_allowed": False,
    },
    "POL-PROHIBIT-01": {
        "code": "POL-PROHIBIT-01",
        "category": "prohibited",
        "title": "Mandatory Human Escalation / Prohibited Agent Actions",
        "citation": "Allowed vs. Prohibited Actions § 4",
        "rule_text": "Prohibited (must escalate to a human agent): Approving any compensation beyond stated policy amounts; Waiving a fare difference above ₹1,500; Making exceptions for non-airline-caused disruptions; Handling threats of legal action or formal complaints; Processing refunds to a different payment method than the original.",
        "prohibited_actions": [
            "compensation_beyond_policy",
            "waiver_above_1500",
            "non_airline_disruption_exception",
            "legal_or_formal_complaint",
            "non_original_refund"
        ]
    }
}
